### ISSUE TITLE
modularize slides

### ISSUE THREAD

**Issue by CrumpLab** [CrumpLab/vertical#12]
vertical currently provides a slides folder, and it is populated with a hard-coded and modified slidy template. I didn't like the slidy defaults, so I added an example of a slide deck that allows custom css.

Making this modular could go a couple different ways. A simple way to go is just have the template builder function create a default slidy template (from the rmarkdown package). Then, the user is left to their own devices to modify that further.

There are lots of different slide packages that could be used here, and anything that generates html could be shared on the website. Not sure how prescriptive vertical should be with respect to loading in templates from slidy or something else like xaringan.

I suppose the absolute simplest thing is to just make a bare slides folder. This approach could be combined with additional vertical functions (or addins) that serve up slide deck templates into the slides folder, and that would be done after the project is loaded.

I think for now I'm going to leave the hard-coded slidy template as is, and get rid of it later as additional functions for loading slide templates are made.

**Comment by mvuorre** [comment]
Yes, it would be neat to allow different kinds of slides. My only concern is that if you include new functions, those basically duplicate existing functionality (e.g. of doing file -> new r markdown -> presentation / xaringan from template). Duplicating functionality may increase complexity, which is bad from a users point of view, but also the cost of maintaining the package, which is bad from a maintainer's point of view.

If you take a look at <https://github.com/mvuorre/vertical/tree/dyndep>, it now asks whether to initialize slides when the project is created. You could add more check boxes to ask which kind(s) of slides to init. (Or one of those scroll down boxes.) But to be honest, once the folder is there (and functionality to copy it to `docs/` when necessary), it will be so easy for users to init new kinds of slides.
