### ISSUE TITLE
Naming a vertical project

### ISSUE THREAD

**Issue by CrumpLab** [CrumpLab/vertical#17]
We note briefly that a vertical project name needs to be a valid project name. I'm considering adding some error checking, and possibly using this `available` package to help out <https://github.com/r-lib/available>

**Comment by CrumpLab** [comment]
hmm, `available` does some weird things, I'll look into a simple function for checking validity only.

**Comment by mvuorre** [comment]
When the project is created, R checks if it is a valid name. So if you give it an invalid name now, it does not work, and fails with an error message.

<img width="420" alt="image" src="https://user-images.githubusercontent.com/7349270/70813450-76e1d400-1d97-11ea-99ee-7e3c7935a0a1.png">

**Comment by CrumpLab** [comment]
perfect, ha, should have tried that.

I was working on adding `init_vertical_project()`, which would allow creation of a vertical project inside an existing project and started thinking about this kind of thing, glads its already taken care of. You had mentioned making something like this earlier, and it would be useful for testing vertical out on fresh R installations. For example, I was in the process of trying to see if vertical would work on RStudio cloud, and ran into the issue that RStudio cloud doesn't load RStudio project templates, so installing vertical there doesn't provide a way to set up the project. So, I'm creating `init_vertical_project()` as a method to create a vertical project inside an existing project on RStudio, and then hopefully run tests on vertical that way.
