### ISSUE TITLE
latex installation issues

### ISSUE THREAD

**Issue by CrumpLab** [CrumpLab/vertical#18]
`papaja` requires a latex installation to knit to pdf. At present, the getting started tutorial mentions this issue and refers to `papaja` documentation for advice on installing latex.

the `tinytex` package may also be useful here. For example, we could include `tinytex` as a dependency, and then check whether latex is installed, and if not run the installation through tinytex... I'm on the fence about whether to include this or not. Another option is to include this information in the tutorial.

**Comment by mvuorre** [comment]
I think it's something that the user should do manually (even tinytex requires running install_tinytex() that installs 200mb of stuff on the user's computer). So I'd recommend not including it as a dependency but including it in the instructions--people should know about tex anyway.

**Comment by CrumpLab** [comment]
Agreed, closing this issue.
