### ISSUE TITLE
Finalize draft manuscript

### ISSUE THREAD

**Issue by CrumpLab** [CrumpLab/vertical#26]
Settle on final draft of the vertical manuscript

**Comment by mvuorre** [comment]
I am pretty happy with the manuscript now, but would like to do more testing on the vertical package before we send it out. (I am happy to post a preprint at this point though.)

**Comment by CrumpLab** [comment]
OK sounds good. Are your manuscript changes now all in rparp master?

Also, not sure if you saw this here, I enhanced the `init_vertical_project()` function so it can create projects from the command line either directly or with some ui dialogue. I tested a bunch of times and found it to be working, but definitely on board with more testing.

**Comment by mvuorre** [comment]
Yup, they are on the master branch.

The function looks good. Now the issue is that there are two functions that do the same thing (init_vertical_project and vertical_project) and one should therefore be removed.

**Comment by CrumpLab** [comment]
Great, got it and I read over your changes to the manuscript, and liked all of them. I noticed an XXX in the data storage section, so I assume you had something in mind for that.

Also, any title preferences, or go with what's currently there?

I could see some issues merging these two functions, given that one is assuming inputs from a .dcf file. A good first step to resolve this might be to hide `vertical_project()` from the documentation, but keep it in place for now to manage the R studio template?

But overall, you're right that we should keep one function for the basic job. Let me stew on how to merge this, but for now I'll take `vertical_project()` out of the documentation so it doesn't confuse users.

**Comment by mvuorre** [comment]
Oops, yes I definitely need to proof read the entire thing. It is fixed now.

I'll take another look at the title, I'd like it to be shorter.

Yes at least the vertical_project should be internal and not exported. After that the only pain is that keeping two functions makes maintaining vertical more complicated.

**Comment by CrumpLab** [comment]
I have a fix for the redundant function issue, it's pushed to `tesbuild` branch, which was updated with master, and now includes a change to `vertical_project()`. That function is now defined as:

```
vertical_project <- function(path, ...) {
  init_vertical_project(project_name = path,
                        project_path = getwd(),
                        ...)
}
```

So, it basically calls `init_vertical_project` with the parameters it receives from the dcf file when users use the template to create it. I tested it and it seems to work without problems. This seems like a decent solution in terms of simplifying maintenance.

I noticed the documentation for `vertical_project()` was added back in, what's your thought on that. I suppose I would go with the above definition, and remove from documentation?

**Comment by mvuorre** [comment]
See #41, which implements a simpler (only in my opinion of course) solution: For starters, it is confusing to have separate arguments for name and path. Also, a one-function solution is easier to maintain (not to mention that #41 has a much shorter function.)

Sorry about the duplicated work.

**Comment by CrumpLab** [comment]
I'm ready to say we have a final draft. I'll leave the final decision to you, so when you agree weigh in here and/or close this issue.

**Comment by CrumpLab** [comment]
It seems we've finalized the draft, which is now located in `/manuscript` in this repo. closing.
