### ISSUE TITLE
increment version to 1.0

### ISSUE THREAD

**Issue by CrumpLab** [CrumpLab/vertical#29]
On submission, increment vertical version to 1.0

**Comment by CrumpLab** [comment]
I'm anticipating we are nearing a 1.0 release. I've merged the current dev to master and incremented the version to 0.0.0.9900.

I'll suggest we increment to 1.0 when we are are ready to submit. Also, I'd like to clean up the branch structure to include only master and dev, so if you are ok with that let me know and I'll delete the other branches.

**Comment by mvuorre** [comment]
I am happy with that. You can delete the other branches.

**Comment by CrumpLab** [comment]
done, closing this issue (version is now 0.0.1.0000)
