### ISSUE TITLE
Include poster template

### ISSUE THREAD

**Issue by mvuorre** [CrumpLab/vertical#3]
Basically there seem to be two options:

<https://github.com/rstudio/pagedown#posters>, and
<https://github.com/brentthorne/posterdown>.

The latter seems more straightforward so I would recommend that. There are three templates so a default should be chosen.

I can hopefully do a PR late this week if the feature seems ok.

**Comment by CrumpLab** [comment]
posterdown looks good, let's go with that. Not sure which one to use as a default, maybe the posterdown_html, which is more of a recognizable default style

**Comment by mvuorre** [comment]
Great, I will take a look and send a PR--but maybe after thinking about #4 (currently, every `posterdown` update would suggest a manual `vertical` update.)

**Comment by mvuorre** [comment]
This was implemented in PR #15
