### ISSUE TITLE
Don't overwrite _pkgdown.yml by default

### ISSUE THREAD

**Issue by mvuorre** [CrumpLab/vertical#30]
I'd prefer

```
vertical::build_vertical(update_yml = FALSE, ...)
```

to be default. I just did lost of manual edits to the file, and wanted to recompile the website. I was surprised to see that my manual edits were gone. I anticipate users will want to usually edit that file by hand so turning yml updating off by default seems reasonable.

**Comment by CrumpLab** [comment]
Makes sense to me, sorry you lost those changes! I'll make the fix pronto

**Comment by mvuorre** [comment]
No worries nothing was lost due to git magic, but I was just surprised to see it happen (I guess I should check default arguments more often...)

**Comment by CrumpLab** [comment]
now fixed in the master
