### ISSUE TITLE
`document_data()`

### ISSUE THREAD

**Issue by mvuorre** [CrumpLab/vertical#31]
https://github.com/CrumpLab/vertical/blob/5f6c66f5edc22d1b633f76333af37631ff57d0f5/R/vertical_project.R#L480

There is a bug in `document_data()`:

```
dat <- data.frame(x = 1)
vertical::document_data(dat)
# Then click '1' to add roxygen skeleton
```

I now have an empty `R/dat.R`, and a `R/mydf.R` with:

```
#' @title DATASET_TITLE
#' @description DATASET_DESCRIPTION
#' @format A data frame with 1 rows and 1 variables:
#' \describe{
#'   \item{\code{x}}{double COLUMN_DESCRIPTION} 
#'}
#' @details DETAILS
"dat"
```

More broadly, I think this function unnecessarily duplicates functioning of `usethis::` functions, which makes the vertical package more difficult to maintain, and complicates matters from the user's perspective (ie  they don't know if they are using vertical functionality or usethis functionality.) I suggest taking out this function as it can be replaced with one or two `usethis::` calls. I also hesitate to mention this in the MS because the overhead makes it less likely to be well maintained compared to the usethis functions (plus added complexity for users).

Edit: Maybe the above is not a bug but I found it confusing: Why do I have two new files in `R/`?

**Comment by CrumpLab** [comment]
Definitely a bug, just updated it, should be working now, and shouldn't produce to files in `R/`. Thanks for catching that.

I'm on the fence about taking this out, but I largely agree with your points. The getting started tutorial describes two examples for documenting data, one using the `usethis` functions and `sinew` function, and the other using `document_data()`. I suppose for me I would find the `document_data()` function convenient as a wrapper function.

I wonder about a proposal that is sort of in between. If we kept the function I would suggest listing it under a new section in the reference list, something like "convenience functions". Then inside the documentation for this function we could provide clear advice about using it (e.g., that it is wrapping other functions), perhaps mention a kind of "use with the understanding that if the underlying functions change this will change", and also describe how to use the base functions...This all does seem complicated from the point of view of maintaining vertical. Too bad usethis doesn't have a sinew option for automatically including roxygen comments.

**Comment by CrumpLab** [comment]
I woke up agreeing with you more about canning `document_data()`. The function is hacky anyway, and can't handle multiple data frames. I'm going to update vertical with this removed, and possibly add another example of using `sinew` which is pretty great.

**Comment by CrumpLab** [comment]
`document_data()` is now removed from the package, and the getting started tutorial has been updated.

**Comment by mvuorre** [comment]
I agree this might be the best solution. Closing issue now.
