### ISSUE TITLE
experiment not found on website

### ISSUE THREAD

**Issue by mvuorre** [CrumpLab/vertical#34]
I created a new project, chose not to include an experiment (default). Website still includes a link to experiment that is not found.

**Comment by CrumpLab** [comment]
Ya, that's currently hardcoded to the default _pkgdown.yml. I'll propose:

1. delete this from the hardcoded default, as a part of simplifying for #36 
2. make a change to update_yml() to recognize experiments folder and add an experiments component if the folder is there

**Comment by mvuorre** [comment]
Sounds perfect

**Comment by CrumpLab** [comment]
I have a working fix. The yml for experiment now gets added if there is an experiments folder. If there happen to be Rmds in the folder or a subfolder (as might happen in a jspsychr experiment), links to those get added as well. However, I don't have it set up to add the link to the experiment.html file, this would have to be added by hand.

I'm going to close this issue, and open another that's related to the `experiments` folder
