### ISSUE TITLE
Source code link

### ISSUE THREAD

**Issue by mvuorre** [CrumpLab/vertical#35]
Created a new project, compiled the website, source code link points to https://github.com/CrumpLab/vertical_template. Can we make it point somewhere else? (Possibly can assume that users will push to github, so something like https://github.com/user/repo)

**Comment by CrumpLab** [comment]
Some options:

1. leave `href` for the source code link blank. Forcing users to fill it in. This has an undesired side effect of not showing the github icon, and writing the text source code in small font.
2. could literally use `https://github.com/user/repo`, actually I do this for now.
3. we may be able to write part of this on creation, for sure I think we can replace repo with the package name. If a github username is in an rprofile, might be able to write the whole thing. 

For now, 2 is probably the best bet.

**Comment by mvuorre** [comment]
2.

Also forces people to think about whether they want to put it on github.

**Comment by CrumpLab** [comment]
perfect, closing this
