### ISSUE TITLE
Don't hard code dependencies

### ISSUE THREAD

**Issue by mvuorre** [CrumpLab/vertical#4]
Currently, components of a project (dependencies, e.g. papaja template, jspsych files) seem to be hard coded into the `vertical` template. If any of those are updated (jspsych already has a newer version I think), the maintainer of `vertical` needs to manually update them.

A better (?) solution would be to have `vertical` create the subcomponents as needed, pulling each from source. There ought to be a way to make `vertical` run a script when the user creates a template; that script could then install the subcomponents into their folders. For R packages it would be easy, for others (jspsych) one could e.g. call git clone. Does that make sense?

**Comment by CrumpLab** [comment]
Agreed, need to think through these dependency issues...

As a step toward doing that, I'm going to list the steps of what currently happens, and then think more about how to address dependency issues.

The vertical template is controlled by three main things. When a new vertical project is created, the `vertical_project.R` function runs...currently it just copies the contents of `inst/vertical` into the project, which contains hard coded copies of the template. Also, the dcf file `inst/rstudio/templates/project/vertical_project.dcf` gives some control over the pop-up options that appear when creating a new project in R-studio. These options can be inputs to the template creation function.

Some of the dependency issues should be resolvable by editing the `vertical_project.R` function. If we wanted to download and install the most recent version of jspsych at the time of template creation, we should be able to do that there.

I'm going to check out Danielle Navarro's `xprmntr` package and see where she is at with that (R package/wrapper for jspsych), it might be easier to build some kind of xprmntr template, and that package might handle the downloading and updating of jspsych.

**Comment by mvuorre** [comment]
Thanks for responding to my ramblings. Here are some more (possibly bad) thoughts on this.

## Make the design on of `vertical` more portable and easier to maintain

One way to get at this would be to not make it a custom project template. Instead, ask users to create a new package (rstudio -> new package), and have `vertical` make all the conveniences easily accessible through a custom build script and add-ins that create modules (see 2.) when needed. Alternatively, the project template could remain, but could be made to get dependencies at init time instead of hard coding them.

## Make the design on of `vertical` more modular

One could see `vertical` as a way to add functionality to the existing r package framework. If so, then `vertical` could provide rstudio add-ins, and/or a custom build script, that initialize additional modules (manuscript, poster, experiment, etc.). Those could be run on a as-needed or 'everything now' basis.

## Don't duplicate existing functionality

Among other things, the `vertical` template initializes a package with `pkgdown`, and provides hard coded dependencies. Dropping the `vertical` template in favor of a more modular approach (above) would allow getting dependencies that are always up to date. If you leave initializing `pkgdown` to the user, that would always be up to date too (and is a one liner if I recall correctly)


The above is a little abstract now but I will put together an example of how it could be implemented. This is of course just a suggestion, but in my experience it is best not to ask users to learn more things, but instead have them learn existing frameworks (pkgdown, etc.). One should avoid adding layers of complexity.

**Comment by CrumpLab** [comment]
I think making vertical more modular is good. For now, I'm going to keep the project template, but begin modifying the script that produces the template to reduce then eliminate hard-coding. To keep track, I'll make  new modular issues for each piece and work incrementally.

**Comment by mvuorre** [comment]
I have a proposal to address this issue and #3, #6 (kind of), some of #9, and #12. You can view it at <https://github.com/mvuorre/vertical/tree/dyndep>. You can get a good idea of how it works by installing it with `remotes::install_github("mvuorre/vertical", ref = "dyndep")` [EDIT: hmm, for some reason it only works if you clone and then install from local, I am looking into why now].

I'm copying the new NEWS.md below:

```
# vertical 0.0.0.9100

This version is a rethinking of vertical's back-end functionality with the goal of making vertical more lightweight and portable.

* Initialize project components from source
  * When a vertical project is created, all subcomponents are pulled from their source, instead of being hard-coded to vertical, making the package more portable, easier to maintain, and lightweight
* Select components
  * When a vertical project is created, users can choose which components to initialize.
* Now includes a poster template
* New contributor: Matti Vuorre
```

**Comment by CrumpLab** [comment]
Nice, these changes look great. Will take a closer look tomorrow morning, but love that you modified the dcf file!

**Comment by mvuorre** [comment]
I see that you had already included papaja and jspsych dynamically so my changes would duplicate those. But overall I think our approaches are converging to something like that. Let me know if you'd like me to send a PR; we would just have to figure out the conflicting papaja and jspsych implementations.

Next step might be to put all of the little bits of code that initialize papaja, jspsych, etc. into their own functions, and then [call those functions at install time](https://github.com/mvuorre/vertical/blob/210f60db0bf496b202b0a2c188e2d5ae5b297cfa/R/vertical_project.R#L83). Then we could include each function as an add-in; if users choose not to include some components at install time, they could do so later from the add-in menu.

**Comment by CrumpLab** [comment]
Got sidetracked a bit this morning. A PR for your changes would be good, I think we're basically on the same page here. And, totally agreed about creating those functions for an addin.

Been spending the morning improving jspsych related issues, and still  working on that, should have  some better examples for using jspsych soon.
