### ISSUE TITLE
update_yml()

### ISSUE THREAD

**Issue by mvuorre** [CrumpLab/vertical#45]
Does `update_yml()` update _pkgdown.yml, or overwrite it completely with what's found in the project root? That is, say I have a manually edited yml file, then I add a extra-analysis/cool-stuff.Rmd; can I then run `update_yml()` so that all the previous manual edits are still there, but now also includes a link to cool-stuff.html? If not, the function should be renamed to something like `overwrite_yml()`, or possibly removed because its likely these files will almost always be manually edited. For example, people will want to remove/edit the link to X link to Y lines.

**Comment by CrumpLab** [comment]
Right now there is some updating and some overwriting. 

It overwrites/adds any yml for vignettes, poster, slides, and manuscript based on titles from documents in those folders.

But, it does not overwrite anything else. If you manually added another component to the yml it would not get overwritten, similarly it doesn't overwrite the links at the end. 

My sense is we leave it there for now, with the default in `build_vertical()` set to FALSE. We can point to this as an option for automating a yml skeleton for a vertical project, that would then be manually edited (e.g., run once then manually edit). 

Overall, I could see some improvements to how vertical handles yml updates, but I need to think through them some more. As a sidenote I came across [ymlthis](http://ymlthis.r-lib.org), which may be helpful for future enhancements.

**Comment by mvuorre** [comment]
See <https://github.com/CrumpLab/vertical/issues/47#issuecomment-568614484>
