### ISSUE TITLE
New vertical project: "Error: `name` argument is missing"

### ISSUE THREAD

**Issue by mvuorre** [CrumpLab/vertical#49]
Creating a new vertical project through GUI: Project -> New Project -> Vertical, ...

```
✔ Creating 'test1/'
✔ Setting active project to '/Users/Matti/Downloads/test1'
✔ Creating 'R/'
✔ Writing 'DESCRIPTION'
Package: test1
Title: What the Package Does (One Line, Title Case)
Version: 0.0.0.9000
Authors@R (parsed):
    * Matti Vuorre <mv2521@columbia.edu> [aut, cre] (<https://orcid.org/0000-0001-5052-066X>)
Description: What the package does (one paragraph).
License: MIT + file LICENSE
Encoding: UTF-8
LazyData: true
✔ Writing 'NAMESPACE'
✔ Writing 'test1.Rproj'
✔ Adding '.Rproj.user' to '.gitignore'
✔ Adding '^test1\\.Rproj$', '^\\.Rproj\\.user$' to '.Rbuildignore'
✔ Opening 'test1/' in new RStudio session
✔ Setting active project to '<no active project>'
✔ Setting active project to '/Users/Matti/Downloads/test1'
✔ Writing '_pkgdown.yml'
✔ Adding '^_pkgdown\\.yml$' to '.Rbuildignore'
Error: `name` argument is missing.
Set it globally with `options(usethis.full_name = "My name")`probably in your '.Rprofile'.
```

test1 RStudio window opens and everything seems to be OK. However the old window remains with the above error with a "Error Creating Project; R code execution error" popup.

RStudio Version 1.2.5033

```
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.2

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.2 tools_3.6.2   
```

**Comment by mvuorre** [comment]
I can get rid of this error when I add `options(usethis.full_name = "My name")` to .Rprofile. I had `options(usethis.name = "My name")` as per previous usethis instructions but that was not sufficient.

But in any case we can't expect users to know that they should have stuff in their .Rprofile. Either we must then fix this or have detailed instructions on what is needed in their .Rprofiles and how to edit that file.

**Comment by CrumpLab** [comment]
Nice catch. I deleted my .Rprofile and reproduced the error.

It seems that `usethis::use_mit_license()` forces a name check, and throws an error if there is no `usethis.full_name = "My name"` in .Rprofile. 

This led to me wonder about how we should deal with licenses. Currently we force inclusion of an mit license, but it's not clear to me that we should be so prescriptive here. For example there are many other licensing options and we don't allow a user to make a decision about the license they want or if they want one. Maybe a better default would be no license. This would solve the problem (e.g., if I comment out `usethis::use_mit_license()` then a new vertical project initializes without a problem even when my .Rprofile is empty).

Alternatively, we could add some check for a name and then add the license or not depending. 

Last, it's a good idea to include pointers about .Rprofiles to the getting started tutorial in general. I'll do that today. But, totally agree that we want to vertical to work out of the box for users that don't have any defaults set in .Rprofile.

**Comment by CrumpLab** [comment]
Here's what I've done in the current `dev` branch. 

1. only initialize with a license if a name exists:

```
if (!is.null(getOption("usethis.full_name"))) usethis::use_mit_license()
```

This solves the name error, and only loads a license if there is a usethis style full_name in the .Rprofile. I mentioned previously that we might consider removing the license altogether. I'm waffling on that, as I can also see the benefits of suggesting a license.

2. made a few small changes to the getting started tutorial. There is pointer to the usethis documentation for editing .Rprofile

I think this fixes the issues?

**Comment by mvuorre** [comment]
I think we should not initialize with a license. We can't decide for the user what license they want, and it is too easy to fall into the default mit license if we include it like that.

**Comment by CrumpLab** [comment]
This is fine with me. I'll take out the license line from the dev branch. Plus, without a license the DESCRIPTION file has a line that asks about the license, which is good for prompting users to think about that rather than accept some default.

**Comment by CrumpLab** [comment]
Alright dev branch is updated, and check still passes with no errors

**Comment by CrumpLab** [comment]
Closing this issue
