### ISSUE TITLE
Does the preprint has a doi ?

### ISSUE THREAD

**Issue by jcolomb** [CrumpLab/vertical#59]
if not, maybe consider pushing it to a platform that creates one ? would help to cite your work.

In addition/alternatively, you may think about archiving the repo on zenodo, and get a doi there.

**Comment by mvuorre** [comment]
Hi @jcolomb, thanks for the questions. OSF preprints (where the preprint is hosted) offers DOIs, and this work is at <https://doi.org/10.31234/osf.io/jks2u>

The article is published at <https://link.springer.com/article/10.3758%2Fs13428-020-01436-x>, and if you cite this work we would appreciate if you cited the published version at BRM.

@CrumpLab It's probably a good idea to include these on the vertical website as well?

**Comment by CrumpLab** [comment]
Oh nice, I didn't realize the paper was officially online. I'll add those links.
