### ISSUE TITLE
Build process

### ISSUE THREAD

**Issue by mvuorre** [CrumpLab/vertical#6]
I think that file could be replaced with a custom build script. That is, there should be a way to make a button into the "build" tab in r studio that creates the website, including all its dependencies, in the right place (and runs whatever else is needed). I can look into it if that would make sense.

**Comment by CrumpLab** [comment]
Agreed we need a vertical build script that handles compiling. I haven't found out how to add things to those tabs in R-studio..an alternative would be an add-in or gadget.

I wouldn't get rid of the Vertical Helper.R completely. The main idea behind that file is to give examples of helpful oneliners (from pkdown or usethis) that people might use (say if they are going to build an R package).

**Comment by mvuorre** [comment]
It would be nice from a user's perspective if I could just click "build" in rstudio, but alas that doesn't seem to be a sustainable route. I have not found a good way to change the build tools such that it would include the default package build tools, *and* whatever custom build tools needed for the other vertical components. 

However, it would be "easy" to create a function that does all the steps necessary to build the vertical project into docs/. Then we could create an add-in that calls the function. How does that sound? (It might be possible to link that function to a Makefile to enable custom build tools, but I'm not sure if that is a sustainable way to do it.)

**Comment by mvuorre** [comment]
There is now some work toward this in the dev branch, which implements a `build_vertical()` function & addin.

**Comment by CrumpLab** [comment]
I've merged your dev version to the master, and looked at `build_vertical()`, which is a highly necessary function. The issue of building a vertical site also relates to yml issues in #9.

Currently, vertical provides a hard coded `_pkgdown.yml` that works for a default template that loads all content modules. For now, I think this is fine. In this method, the user needs to edit the yml by hand to control the assets they want to share. In general, I think this is an ok start for a first release of vertical.

`build_vertical()` also hard codes rendering of specific files in specific folders. Below I'll brainstorm some directions for `build_vertical()`.

1. We should add options to the function, one is a logical for cleaning or not cleaning the site on build. The default could be `clean=TRUE`.
2. add the ability to pass options to `pkgdown::build_site()`
3. We should wrap rendering for each folder with a check to see if the folder exists, and only render if it does exist. I'm not sure what happens right now if one of the folders doesn't exist.
4. Remove hard-coded rendering of specific files...or the option to do so. For example, for each folder we could collect the .Rmd file names that exist, and then render all of them to the `docs` folder. This doesn't force the user to adopt naming conventions for individual files. But, this also requires manual addition of links to those files in the yml...An enhancement would cover automatic additions to the yml file, but that might be easier said than done.
5. Render additional folders...we could add an option to list additional arbitrary folder names, and then render .Rmds in those folders to the docs folder.
6. Handling external content...this could be a separate function. For example, imagine someone wanted to use vertical, but they made their paper in word, a poster in keynote, and a slide deck in powerpoint, or something like that. They could add them manually to the docs folder, but it might be better for them to place those documents in their respective `vertical` folders, and then run a function that automates exporting those files to the docs folder. For example, something like `vertical::include_external(folders = c(), file_type=c())` could scrape a list a folders to find any of the specified file types, and then copy them all to `docs`.

**Comment by mvuorre** [comment]
I agree with all of the above., but 6. might be better implemented with asking users to manually edit the pkgdown.yml file.

**Comment by CrumpLab** [comment]
I pushed an update to the master that handles 1-4. 

There is a new function `update_yml()` that updates the yml in `_pkgdown.yml` automatically on `build_vertical()`.
 
`update_yml()` scrapes each folder (vignettes, manuscript, posters, slides) and adds the title in .Rmd documents in each folder to their respective tabs on the website. For the vignettes folder, if there are sub-folders, the name of the sub-folder is added as a text separator to the tab, which I think provides a useful way of separating content (e.g., vignettes could have a data analysis folder, and a model folder, which results in sections for each in the tab).

**Comment by CrumpLab** [comment]
I've been working on a testbuild branch to improve our building issues. I updated the `init_vertical_project()` function so it can build a project inside an existing project, or create a new project from scratch, basically a command line alternative to setting up the project rather than using the R studio template. It'd be nice to have all 3 of these options. I think it's working now. Need to update the documentation

**Comment by CrumpLab** [comment]
Major building issues are resolved
