### ISSUE TITLE
install dependencies?

### ISSUE THREAD

**Issue by CrumpLab** [CrumpLab/vertical#7]
vertical does not yet install package dependencies...

Related to #4, currently vertical loads example templates (e.g., papaja template to manuscripts, slidy template to slides, etc.) in hard-coded fashion. If a user does not have the packages for compiling these templates, then the templates won't work. 

vertical probably should install package dependencies...which one's should it install?

papaja
posterdown

tidyverse?
knitr?
rmarkdown?

**Comment by mvuorre** [comment]
I think the best way to do this is to include R packages in `DESCRIPTION`, and get others (jspsych) dynamically as latest releases from github when needed. As to what should be included, perhaps consider including all the R components (papaja, posterdown) as `includes` in `DESCRIPTION`, but not include things like tidyverse that are not needed unless the user wants to use them in their scripts.

**Comment by CrumpLab** [comment]
Agreed. Also, I'm realizing I have never done an include for a package that is not on CRAN, I think papaja is not on CRAN. I'm assuming it's possible to have install with dependencies include R packages on github, will check it out.

**Comment by CrumpLab** [comment]
Just leaving this here for my future reference on installing remotes:

[https://cran.r-project.org/web/packages/devtools/vignettes/dependencies.html](https://cran.r-project.org/web/packages/devtools/vignettes/dependencies.html)

**Comment by mvuorre** [comment]
Vertical's R dependencies, including non-CRAN remotes (papaja) are now correctly referred to in DESCRIPTION in the dev branch.

**Comment by CrumpLab** [comment]
I'm going to close this issue, I added `posterdown` to the dependency list, and we can address remaining dependency issues if they pop up.
